title: TRAINING For Reproducibility Verification (CIQSS/QICSS version)
logo: LDIimage_11.22.19_FINALv1.jpg
description: Training for reproducibility, customized for the context of CIQSS/QICSS.
show_downloads: false
theme: jekyll-theme-minimal